version: '3'

services:

  db:
    image: mysql
    networks:
      - shared-net
    environment:
      MYSQL_USER: issuebase
      MYSQL_PASSWORD: issuebase
      MYSQL_DATABASE: issuebase
      MYSQL_ROOT_PASSWORD: issuebase
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - type: bind
        source: ./up.sql
        target: /up.sql

  redis:
    image: redis
    networks:
      - shared-net
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./redis-conf.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  
  tomcat:
    image: issuebase-tomcat:1
    networks:
      - shared-net
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./deploy/tomcat-users.xml
        target: /usr/local/tomcat/conf/tomcat-users.xml
      - type: bind
        source: ./deploy/setenv.sh
        target: /usr/local/tomcat/bin/setenv.sh
      - type: bind
        source: ./deploy/context.xml
        target: /usr/local/tomcat/context.xml
      - type: bind
        source: ./deploy/settings.xml
        target: /root/.m2/settings.xml
      - type: bind
        source: ~/.m2/
        target: /root/.m2/

volumes:
  db:
    driver: local

networks:
  shared-net:
    driver: bridge